export const FILTER_PRESETS = [
    {
        name: "Normal",
        brightness: 100,
        contrast: 100,
        saturation: 100,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Clarendon",
        brightness: 110,
        contrast: 125,
        saturation: 120,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 5,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Gingham",
        brightness: 105,
        contrast: 90,
        saturation: 100,
        blur: 0,
        grayscale: 20,
        sepia: 10,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Moon",
        brightness: 100,
        contrast: 100,
        saturation: 0,
        blur: 0,
        grayscale: 100,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Lark",
        brightness: 110,
        contrast: 90,
        saturation: 115,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Reyes",
        brightness: 110,
        contrast: 85,
        saturation: 75,
        blur: 0,
        grayscale: 0,
        sepia: 22,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Juno",
        brightness: 100,
        contrast: 115,
        saturation: 180,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Willow",
        brightness: 95,
        contrast: 90,
        saturation: 0,
        blur: 0,
        grayscale: 100,
        sepia: 20,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Inkwell",
        brightness: 100,
        contrast: 110,
        saturation: 0,
        blur: 0,
        grayscale: 100,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Valencia",
        brightness: 108,
        contrast: 110,
        saturation: 100,
        blur: 0,
        grayscale: 0,
        sepia: 15,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "X-Pro II",
        brightness: 90,
        contrast: 130,
        saturation: 150,
        blur: 0,
        grayscale: 0,
        sepia: 30,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Lo-Fi",
        brightness: 95,
        contrast: 140,
        saturation: 130,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Rise",
        brightness: 105,
        contrast: 100,
        saturation: 100,
        blur: 0,
        grayscale: 0,
        sepia: 15,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Amaro",
        brightness: 110,
        contrast: 90,
        saturation: 150,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Earlybird",
        brightness: 110,
        contrast: 90,
        saturation: 150,
        blur: 0,
        grayscale: 0,
        sepia: 20,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Toaster",
        brightness: 90,
        contrast: 150,
        saturation: 100,
        blur: 0,
        grayscale: 0,
        sepia: 25,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Nashville",
        brightness: 110,
        contrast: 120,
        saturation: 100,
        blur: 0,
        grayscale: 0,
        sepia: 20,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Hudson",
        brightness: 120,
        contrast: 100,
        saturation: 110,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: -10,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Ashby",
        brightness: 120,
        contrast: 100,
        saturation: 80,
        blur: 0,
        grayscale: 0,
        sepia: 15,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Hefe",
        brightness: 100,
        contrast: 130,
        saturation: 160,
        blur: 0,
        grayscale: 0,
        sepia: 10,
        hue: 0,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Cyberpunk",
        brightness: 100,
        contrast: 140,
        saturation: 200,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 230,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Cotton Candy",
        brightness: 110,
        contrast: 100,
        saturation: 180,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 270,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Peachy",
        brightness: 105,
        contrast: 100,
        saturation: 140,
        blur: 0,
        grayscale: 0,
        sepia: 10,
        hue: -20,
        invert: 0,
        opacity: 100,
    },
    {
        name: "Vivid",
        brightness: 110,
        contrast: 125,
        saturation: 140,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100
    },
    {
        name: "Cool Tone",
        brightness: 100,
        contrast: 95,
        saturation: 85,
        blur: 0,
        grayscale: 25,
        sepia: 5,
        hue: -15,
        invert: 0,
        opacity: 100
    },
    {
        name: "Sunset",
        brightness: 115,
        contrast: 110,
        saturation: 130,
        blur: 0,
        grayscale: 0,
        sepia: 25,
        hue: 10,
        invert: 0,
        opacity: 100
    },
    {
        name: "Faded",
        brightness: 90,
        contrast: 80,
        saturation: 70,
        blur: 5,
        grayscale: 0,
        sepia: 15,
        hue: 0,
        invert: 0,
        opacity: 100
    },
    {
        name: "Retro",
        brightness: 100,
        contrast: 115,
        saturation: 120,
        blur: 0,
        grayscale: 0,
        sepia: 20,
        hue: 10,
        invert: 0,
        opacity: 100
    },
    {
        name: "Dusk",
        brightness: 105,
        contrast: 100,
        saturation: 90,
        blur: 0,
        grayscale: 15,
        sepia: 5,
        hue: -10,
        invert: 0,
        opacity: 100
    },
    {
        name: "Vintage",
        brightness: 100,
        contrast: 90,
        saturation: 85,
        blur: 0,
        grayscale: 10,
        sepia: 30,
        hue: 0,
        invert: 0,
        opacity: 100
    },
    {
        name: "Neutral",
        brightness: 100,
        contrast: 100,
        saturation: 100,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        hue: 0,
        invert: 0,
        opacity: 100
    }
];
